=== CameronBeeler/XMLTest/src/com/cameronbeeler/patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.cambeeler.com/Patient"
        xmlns:cwb="http://www.cambeeler.com/Patient"
        elementFormDefault="qualified">

    <element name="patient" type="cwb:Patient" />

    <complexType name="Patient">
        <sequence>
            <element name="id"      type="cwb:ID" />
            <element name="name"    type="string"/>
            <element name="age"     type="int"/>
            <element name="dob"     type="date"/>
            <element name="email"   type="string"/>
            <element name="gender"  type="string"/>
            <element name="phone"   type="string"/>
            <element name="payment" type="cwb:PaymentType"/>
            <element name="any"     type="string" />
        </sequence>
    </complexType>

    <complexType name="PaymentType">
        <choice>
            <element name="cash" type="int" />
            <element name="insurance" type="cwb:Insurance" />
        </choice>
    </complexType>

    <complexType name="Insurance">
        <all>
            <element name="provider" type="string" />
            <element name="limit" type="int" />
        </all>
    </complexType>

    <simpleType name="ID">
        <restriction base="int">
            <pattern value="[0-9]*"/>
        </restriction>
    </simpleType>

    <simpleType name="Name15Chars">
        <restriction base="string">
            <maxLength value="15"/>
            <pattern value="[a-z A-Z]*"/>
        </restriction>
    </simpleType>

    <simpleType name="Gender">
        <restriction base="string">
            <enumeration value="M"/>
            <enumeration value="F"/>
        </restriction>
    </simpleType>
</schema>

=== CameronBeeler/XMLTest/src/com/cameronbeeler/Patient2.xml
<?xml version="1.0" encoding="UTF-8"?>
<cwb:patient xmlns:cwb="http://www.cambeeler.com/Patient"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.cambeeler.com/Patient Patient.xsd ">
  <cwb:id>2</cwb:id>
  <cwb:name>Cameron Beeler</cwb:name>
  <cwb:age>50</cwb:age>
  <cwb:dob>1968-01-25</cwb:dob>
  <cwb:email>cameron.beeler@gmail.com</cwb:email>
  <cwb:gender>M</cwb:gender>
  <cwb:phone>4792505466</cwb:phone>
  <cwb:payment>
    <cwb:cash>125</cwb:cash>
  </cwb:payment>
  <cwb:any>stuff stuff</cwb:any>
</cwb:patient>

=== CameronBeeler/XMLTest/src/com/cameronbeeler/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>

<cwb:patient xmlns:cwb="http://www.cambeeler.com/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cambeeler.com/Patient Patient.xsd " id="1">

    <!--<cwb:id>1</cwb:id>-->
  <cwb:name>CamBeeler</cwb:name>
  <cwb:age>50</cwb:age>
  <cwb:dob>1968-01-25</cwb:dob>
  <cwb:email>cameron.beeler@gmail.com</cwb:email>
  <cwb:gender>M</cwb:gender>
  <cwb:phone>4792505466</cwb:phone>
  <cwb:payment>
    <cwb:insurance>
 	    <cwb:limit>1000</cwb:limit>
    	<cwb:provider>BCBS</cwb:provider>
   	</cwb:insurance>
  </cwb:payment>
    <cwb:any>anything here</cwb:any>
</cwb:patient>
